"""Add timestamps, scheduled_transactions, net_worth constraint

Revision ID: af63e055055a
Revises: c3d4e5f6g7h8
Create Date: 2026-02-21 18:37:57.625407

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = "af63e055055a"
down_revision: str | None = "c3d4e5f6g7h8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _existing_indexes(table: str) -> set[str]:
    """Reflect the index names currently on ``table``."""
    inspector = sa.inspect(op.get_bind())
    return {idx["name"] for idx in inspector.get_indexes(table) if idx.get("name")}


def upgrade() -> None:
    bind = op.get_bind()
    owners = bind.execute(sa.text("SELECT id FROM users ORDER BY id LIMIT 2")).scalars().all()
    has_tax_records = bind.execute(sa.text("SELECT 1 FROM tax_records LIMIT 1")).first() is not None
    if has_tax_records and len(owners) != 1:
        raise RuntimeError(
            "Legacy tax records need an explicitly identified owner before this migration."
        )
    transaction_type = ENUM(
        "EXPENSE", "INCOME", "TRANSFER", name="transactiontype", create_type=False
    )
    if bind.dialect.name == "postgresql":
        # Historical transactions tables may use VARCHAR and have no enum.
        transaction_type.create(bind, checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scheduled_transactions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("amount", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("type", transaction_type, nullable=False),
        sa.Column("category", sa.String(length=255), nullable=False),
        sa.Column("subcategory", sa.String(length=255), nullable=True),
        sa.Column("account", sa.String(length=255), nullable=False),
        sa.Column(
            "frequency",
            sa.Enum(
                "DAILY",
                "WEEKLY",
                "BIWEEKLY",
                "MONTHLY",
                "QUARTERLY",
                "YEARLY",
                name="recurrencefrequency",
            ),
            nullable=False,
        ),
        sa.Column("expected_day", sa.Integer(), nullable=True),
        sa.Column("next_due_date", sa.DateTime(), nullable=False),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("recurring_transaction_id", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scheduled_transactions_is_active"),
        "scheduled_transactions",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheduled_transactions_next_due_date"),
        "scheduled_transactions",
        ["next_due_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheduled_transactions_user_id"),
        "scheduled_transactions",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_scheduled_user_active", "scheduled_transactions", ["user_id", "is_active"], unique=False
    )
    # The index/constraint names below are the ones create_all() produces. A
    # database built from migrations names them differently (or not at all), so
    # every drop is guarded on reflection and every constraint add goes through
    # batch mode -- SQLite has no ALTER TABLE ... ADD CONSTRAINT.
    account_indexes = _existing_indexes("account_classifications")
    if "ix_account_classifications_account_name" in account_indexes:
        op.drop_index(
            op.f("ix_account_classifications_account_name"), table_name="account_classifications"
        )
    op.create_index(
        op.f("ix_account_classifications_account_name"),
        "account_classifications",
        ["account_name"],
        unique=False,
    )
    with op.batch_alter_table("account_classifications") as batch_op:
        batch_op.create_foreign_key(
            "fk_account_classifications_user_id", "users", ["user_id"], ["id"]
        )

    net_worth_indexes = _existing_indexes("net_worth_snapshots")
    for name in ("ix_net_worth_date", "ix_net_worth_user"):
        if name in net_worth_indexes:
            op.drop_index(op.f(name), table_name="net_worth_snapshots")
    op.create_index(
        "ix_net_worth_user_date", "net_worth_snapshots", ["user_id", "snapshot_date"], unique=False
    )
    with op.batch_alter_table("net_worth_snapshots") as batch_op:
        batch_op.create_unique_constraint("uq_net_worth_user_date", ["user_id", "snapshot_date"])

    op.add_column("tax_records", sa.Column("user_id", sa.Integer(), nullable=True))
    if has_tax_records:
        bind.execute(sa.text("UPDATE tax_records SET user_id = :owner"), {"owner": owners[0]})
    tax_indexes = _existing_indexes("tax_records")
    for name in ("ix_tax_records_financial_year", "ix_tax_records_fy"):
        if name in tax_indexes:
            op.drop_index(op.f(name), table_name="tax_records")
    op.create_index(
        "ix_tax_records_user_fy", "tax_records", ["user_id", "financial_year"], unique=False
    )
    op.create_index(op.f("ix_tax_records_user_id"), "tax_records", ["user_id"], unique=False)
    with op.batch_alter_table("tax_records") as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.Integer(), nullable=False)
        batch_op.create_foreign_key("fk_tax_records_user_id", "users", ["user_id"], ["id"])
    with op.batch_alter_table("transactions") as batch_op:
        for name in ("created_at", "updated_at"):
            batch_op.add_column(
                sa.Column(
                    name,
                    sa.DateTime(),
                    nullable=False,
                    server_default=sa.func.current_timestamp(),
                )
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "updated_at")
    op.drop_column("transactions", "created_at")
    op.drop_constraint(None, "tax_records", type_="foreignkey")
    op.drop_index(op.f("ix_tax_records_user_id"), table_name="tax_records")
    op.drop_index("ix_tax_records_user_fy", table_name="tax_records")
    op.create_index(op.f("ix_tax_records_fy"), "tax_records", ["financial_year"], unique=False)
    op.create_index(
        op.f("ix_tax_records_financial_year"), "tax_records", ["financial_year"], unique=False
    )
    op.drop_column("tax_records", "user_id")
    op.drop_constraint("uq_net_worth_user_date", "net_worth_snapshots", type_="unique")
    op.drop_index("ix_net_worth_user_date", table_name="net_worth_snapshots")
    op.create_index(op.f("ix_net_worth_user"), "net_worth_snapshots", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_net_worth_date"), "net_worth_snapshots", ["snapshot_date"], unique=False
    )
    op.drop_constraint(None, "account_classifications", type_="foreignkey")
    op.drop_index(
        op.f("ix_account_classifications_account_name"), table_name="account_classifications"
    )
    op.create_index(
        op.f("ix_account_classifications_account_name"),
        "account_classifications",
        ["account_name"],
        unique=1,
    )
    op.drop_index("ix_scheduled_user_active", table_name="scheduled_transactions")
    op.drop_index(op.f("ix_scheduled_transactions_user_id"), table_name="scheduled_transactions")
    op.drop_index(
        op.f("ix_scheduled_transactions_next_due_date"), table_name="scheduled_transactions"
    )
    op.drop_index(op.f("ix_scheduled_transactions_is_active"), table_name="scheduled_transactions")
    op.drop_table("scheduled_transactions")
    # ### end Alembic commands ###
